# Generated by Django 4.0 on 2024-09-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.CharField(blank=True, max_length=100, null=True)),
                ('user2', models.CharField(blank=True, max_length=100, null=True)),
                ('user3', models.CharField(blank=True, max_length=100, null=True)),
                ('finalUser1', models.CharField(blank=True, max_length=100, null=True)),
                ('finalUser2', models.CharField(blank=True, max_length=100, null=True)),
                ('user4', models.CharField(blank=True, max_length=100, null=True)),
                ('user1Score', models.IntegerField(default=0)),
                ('user2Score', models.IntegerField(default=0)),
                ('user3Score', models.IntegerField(default=0)),
                ('user4Score', models.IntegerField(default=0)),
                ('finalUser1Score', models.IntegerField(default=0)),
                ('finalUser2Score', models.IntegerField(default=0)),
                ('roomNumber', models.IntegerField(default=0)),
                ('winner', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
