# Generated by Django 4.0 on 2024-09-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_host', models.CharField(blank=True, max_length=100, null=True)),
                ('username_guest', models.CharField(blank=True, max_length=100, null=True)),
                ('hostScore', models.IntegerField(default=0)),
                ('guestScore', models.IntegerField(default=0)),
                ('roomNumber', models.CharField(max_length=100)),
                ('winner', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
